#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""手动合并语义节点到 graph.json"""
import json
from pathlib import Path

INPUT_DIR = Path(r"E:\workspace\knowledge-base")
OUTPUT_DIR = INPUT_DIR / "graphify-out"
STATE_FILE = OUTPUT_DIR / "semantic_state.json"

print("=" * 60)
print("Graphify 语义合并")
print("=" * 60)

# 加载 state
if not STATE_FILE.exists():
    print("ERROR: semantic_state.json not found")
    exit(1)

state = json.loads(STATE_FILE.read_text(encoding="utf-8", errors="replace"))
print(f"Loaded state: {len(state['processed'])} processed, {len(state['all_nodes'])} nodes, {len(state['all_edges'])} edges")

# 读取现有 graph.json
graph_file = OUTPUT_DIR / "graph.json"
existing_nodes = []
existing_edges = []

if graph_file.exists():
    existing = json.loads(graph_file.read_text(encoding="utf-8", errors="replace"))
    existing_nodes = existing.get("nodes", [])
    existing_edges = existing.get("edges", [])
    print(f"Existing graph: {len(existing_nodes)} nodes, {len(existing_edges)} edges")

# 去重合并
existing_ids = {n["id"] for n in existing_nodes}
new_nodes = [n for n in state["all_nodes"] if n["id"] not in existing_ids]
merged_nodes = existing_nodes + new_nodes
merged_edges = existing_edges + state["all_edges"]

print(f"\nMerging:")
print(f"  Existing nodes: {len(existing_nodes)}")
print(f"  New nodes: {len(new_nodes)}")
print(f"  Merged nodes: {len(merged_nodes)}")
print(f"  Merged edges: {len(merged_edges)}")

# 保存
merged_graph = {"nodes": merged_nodes, "edges": merged_edges}
graph_file.write_text(json.dumps(merged_graph, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"\nSaved to: {graph_file}")

# 删除 state
STATE_FILE.unlink()
print("Deleted semantic_state.json")

# 生成 GRAPH_REPORT
report = f"""# Graphify Graph Report
Generated by AST + Semantic extraction

## Statistics
- Total nodes: {len(merged_nodes)}
- Total edges: {len(merged_edges)}
- Code files processed (AST): 33606
- Wiki files processed (Semantic): {len(state['processed'])}

## Node Breakdown
- AST nodes: {len(existing_nodes)}
- Semantic nodes: {len(new_nodes)}
"""

report_file = OUTPUT_DIR / "GRAPH_REPORT.md"
report_file.write_text(report, encoding="utf-8")
print(f"Updated: {report_file}")

print()
print("=" * 60)
print("DONE! Semantic extraction complete.")
print("=" * 60)
