#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Graphify AST Only Pipeline (Free - No LLM)
方案A：只提取代码结构，不调用 LLM
"""
import os
import json
from pathlib import Path
from graphify.extract import collect_files, extract
from graphify.build import build
from graphify.cluster import cluster

print('=' * 60)
print('Graphify AST Only Pipeline (Free - No LLM)')
print('=' * 60)

INPUT = Path(r'E:\workspace\knowledge-base')
OUTPUT = Path(r'E:\workspace\knowledge-base\graphify-out')
OUTPUT.mkdir(exist_ok=True)

# Step 1: Collect code files
print('[1/4] Detecting code files...')
code_files = []
for ext in ['.py', '.js', '.ts', '.tsx', '.jsx', '.go', '.java', '.c', '.cpp', '.h', '.rs', '.rb', '.php', '.cs', '.swift', '.kt', '.scala', '.lua', '.sh', '.ps1', '.bat', '.sql', '.yaml', '.yml', '.toml', '.json', '.md', '.txt']:
    code_files.extend(INPUT.rglob(f'*{ext}'))
code_files = [f for f in code_files if f.is_file() and not any(p.startswith('graphify-out') or p.startswith('.git') for p in f.parts)]
print(f'      Found {len(code_files)} code files')

# Step 2: AST extraction
print('[2/4] Running AST extraction...')
result = extract(code_files, cache_root=OUTPUT)
nodes = result.get('nodes', [])
edges = result.get('edges', [])
print(f'      AST: {len(nodes)} nodes, {len(edges)} edges')

# Step 3: Build graph
print('[3/4] Building NetworkX graph...')
G = build([result])
print(f'      Graph: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges')

# Step 4: Community detection
print('[4/4] Running community detection...')
communities = cluster(G)
print(f'      Found {len(communities)} communities')

# Save outputs
graph_data = {
    'nodes': [{'id': n, 'label': G.nodes[n].get('label', str(n)), 'file_type': G.nodes[n].get('file_type', 'unknown')} for n in G.nodes()],
    'edges': [{'source': u, 'target': v, 'relation': G.edges[u, v].get('relation', 'calls')} for u, v in G.edges()]
}
(OUTPUT / 'graph.json').write_text(json.dumps(graph_data, indent=2, ensure_ascii=False))
(OUTPUT / 'communities.json').write_text(json.dumps(communities, indent=2, ensure_ascii=False))

# Generate simple report
report_lines = [
    '# Graphify Graph Report\n',
    f'Generated by AST-only extraction (no LLM)\n',
    f'\n## Statistics\n',
    f'- Total nodes: {G.number_of_nodes()}\n',
    f'- Total edges: {G.number_of_edges()}\n',
    f'- Communities: {len(communities)}\n',
    f'- Code files processed: {len(code_files)}\n',
    f'\n## Top Communities\n',
]
for i, (comm_id, comm_nodes) in enumerate(sorted(communities.items(), key=lambda x: -len(x[1]))[:10]):
    report_lines.append(f'\n### Community {comm_id} ({len(comm_nodes)} nodes)\n')
    for n in comm_nodes[:5]:
        label = G.nodes[n].get('label', str(n)) if n in G else str(n)
        report_lines.append(f'- {label}\n')
    if len(comm_nodes) > 5:
        report_lines.append(f'- ... and {len(comm_nodes) - 5} more\n')

report = ''.join(report_lines)
(OUTPUT / 'GRAPH_REPORT.md').write_text(report, encoding='utf-8')

print()
print('=' * 60)
print(f'Done! Output saved to graphify-out/')
print(f'   - graph.json: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges')
print(f'   - GRAPH_REPORT.md: {len(report)} chars')
print(f'   - communities.json: {len(communities)} communities')
print('=' * 60)
